version: '2'
services:
  nginxforodoo:
    build: ./nginxforodoo
    depends_on:
      - odoo
    ports:
      - "80:80"
      - "443:443"
  odoo:
    image: odoo:10.0
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    environment:
    - HOST=odoodb
    - USER=odoo
    - PASSWORD=myodoo  
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
  odoodb:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
